local _, MilaUI = ...

-- Initialize defaults table if it doesn't exist
MilaUI.Defaults = MilaUI.Defaults or {}

-- Unitframes defaults  
MilaUI.Defaults.Unitframes = {
    migrated = false,       
    General = {
        Font                              = "Expressway",
        FontFlag                          = "OUTLINE",
        FontShadowColour                  = {0, 0, 0, 1},
        FontShadowXOffset                 = 0,
        FontShadowYOffset                 = 0,
        ForegroundTexture                 = "Interface\\RaidFrame\\Raid-Bar-Hp-Fill",
        AbsorbTexture                     = "AbsorbBar",
        BackgroundTexture                 = "Smooth",
        BorderTexture                     = "Interface\\Buttons\\WHITE8X8",
        BackgroundColour                  = {26 / 255, 26 / 255, 26 / 255, 1},
        ForegroundColour                  = {26 / 255, 26 / 255, 26 / 255, 1},
        BorderColour                      = {0 / 255, 0 / 255, 0 / 255, 1},
        BorderSize                        = 1,
        BorderInset                       = 1,
        ColourByPlaterNameplates          = true,
        ColourByClass                     = true,
        ColourByReaction                  = true,
        ColourIfDisconnected              = true,
        ColourIfTapped                    = true,
        ColourBackgroundByForeground      = false,
        ColourBackgroundByClass           = false,
        ColourBackgroundIfDead            = false,
        BackgroundMultiplier              = 0.25,
        CustomColours = {
            Reaction = {
                [1] = {255/255, 64/255, 64/255},            -- Hated
                [2] = {255/255, 64/255, 64/255},            -- Hostile
                [3] = {255/255, 128/255, 64/255},           -- Unfriendly
                [4] = {255/255, 255/255, 64/255},           -- Neutral
                [5] = {64/255, 255/255, 64/255},            -- Friendly
                [6] = {64/255, 255/255, 64/255},            -- Honored
                [7] = {64/255, 255/255, 64/255},            -- Revered
                [8] = {64/255, 255/255, 64/255},            -- Exalted
            },
            Power = {
                [0] = {0, 0, 1},            -- Mana
                [1] = {1, 0, 0},            -- Rage
                [2] = {1, 0.5, 0.25},       -- Focus
                [3] = {1, 1, 0},            -- Energy
                [6] = {0, 0.82, 1},         -- Runic Power
                [8] = {0.3, 0.52, 0.9},     -- Lunar Power
                [11] = {0, 0.5, 1},         -- Maelstrom
                [13] = {0.4, 0, 0.8},       -- Insanity
                [17] = {0.79, 0.26, 0.99},  -- Fury
                [18] = {1, 0.61, 0}         -- Pain
            },
            Status = {
                [1] = {255/255, 64/255, 64/255},           -- Dead
                [2] = {153/255, 153/255, 153/255}, -- Tapped 
                [3] = {0.6, 0.6, 0.6}, -- Disconnected
            }
        },
        MouseoverHighlight = {
            Enabled = true,
            Style = "BORDER",
            Colour = {1, 1, 1, 1},
        },
        CastbarSettings = {
            font = "Expressway",
            fontSize = 10,
            fontFlags = "OUTLINE",
        },
    },
    Player = {
        Frame = {
            Enabled             = true,
            CustomScale         = false,
            Scale               = 1,
            Width               = 230,
            Height              = 38,
            XPosition           = -300,
            YPosition           = -150,
            AnchorFrom          = "LEFT",
            AnchorTo            = "CENTER",
            AnchorParent        = "UIParent",
        },
        Portrait = {
            Enabled         = false,
            Size            = 42,
            XOffset         = -1,
            YOffset         = 0,
            AnchorFrom      = "RIGHT",
            AnchorTo        = "LEFT",
        },
        Health = {
            Width               = 230,
            Height              = 38,
            Direction           = "LR",
            Texture             = "Smooth",
            BackgroundTexture   = "Smooth",
            Colors = {
                ColorByStaticColor                = false,
                StaticColor                       = {1, 1, 1},
                ColourByClass                     = true,
                ColourByReaction                  = true,
                ColourIfDisconnected              = true,
                ColourIfTapped                    = true,
                ColorBackgroundByStaticColor      = false,
                BackgroundStaticColor             = {1, 1, 1},
                ColourBackgroundByForeground      = false,
                ColourBackgroundByClass           = false,
                ColourBackgroundIfDead            = false,
                BackgroundMultiplier              = 0.25,
                Status = {
                    [1] = {255/255, 64/255, 64/255},           -- Dead
                    [2] = {153/255, 153/255, 153/255}, -- Tapped 
                    [3] = {0.6, 0.6, 0.6}, -- Disconnected
                }
                
            },
            CustomMask = {
                Enabled = true,
                MaskTexture = "Interface\\Addons\\Mila_UI\\Media\\Statusbars\\Masks\\parallelogram_style2.tga",
            },
            CustomBorder = {
                Enabled = true,
                BorderTexture = "Interface\\Addons\\Mila_UI\\Media\\Borders\\Custom\\border_style2.tga",
            },
            HealthPrediction = {
                Enabled = true,
                IncomingHeals = {},
                HealAbsorbs = {
                    Enabled = true,
                    Colour = {128/255, 64/255, 255/255, 1},
                },
                Absorbs = {
                    Enabled         = true,
                    Colour          = {255/255, 205/255, 0/255, 1},
                    ColourByType    = true,
                }
            }
        },
        PowerBar = {
            Width                   = 219,
            Height                  = 19,
            XPosition               = 0,
            YPosition               = 0,
            AnchorFrom              = "TOPRIGHT",
            AnchorTo                = "BOTTOMRIGHT",
            AnchorParent            = "MilaUI_Player",
            Direction               = "LR",
            Texture                 = "Smooth",
            BackgroundTexture       = "Smooth",
            
            CustomMask = {
                Enabled = true,
                MaskTexture = "Interface\\Addons\\Mila_UI\\Media\\Statusbars\\Masks\\parallelogram_power_style2.tga",
            },
            CustomBorder = {
                Enabled = true,
                BorderTexture = "Interface\\Addons\\Mila_UI\\Media\\Borders\\Custom\\power_border_style2.tga",
            },
            Enabled                 = true,
            ColourByType            = true,
            ColourBackgroundByType  = true,
            BackgroundMultiplier    = 0.25,
            Colour                  = {0/255, 0/255, 1/255, 1},
            BackgroundColour        = {26 / 255, 26 / 255, 26 / 26 / 255, 1},
            Smooth = false,
        },
        Castbar = {
            enabled = true,
            CustomScale = false,
            Scale = 1,
            CustomMask = {
                Enabled = true,
                MaskTexture = "Interface\\Addons\\Mila_UI\\Media\\Statusbars\\Masks\\parallelogram_power_style2.tga",
            },
            CustomBorder = {
                Enabled = true,
                BorderTexture = "Interface\\Addons\\Mila_UI\\Media\\Borders\\Custom\\power_border_style2.tga",
            },
            width = 200,
            height = 20,
            texture = "Smooth",
            backgroundColor = {0.1, 0.1, 0.1, 0.8},
            border = false,
            borderColor = {0, 0, 0, 1},
            borderSize = 1,
            showShield = true,
            showSafeZone = true,
            safeZoneColor = {1, 0, 0, 0.6},
            timeToHold = 0.5,         -- How long to show failed/interrupted casts
            hideTradeSkills = false,  -- Whether to hide profession casts
            textures = {
                channel = "Smooth",
                cast = "Smooth",
                uninterruptible = "Smooth",
                castcolor = {1, 0.7, 0, 1},
                channelcolor = {0, 0.7, 1, 1},
                uninterruptiblecolor = {0.7, 0, 0, 1},
                failedcolor = {1, 0.3, 0.3, 1},
            },
            Icon = {
                showIcon = true,
                iconSize = 24,
                iconPosition = "LEFT",    -- LEFT or RIGHT
            },
            Spark = {
                showSpark = true,
                sparkWidth = 10,
                sparkHeight = 30,
                sparkTexture = "Interface\\Buttons\\WHITE8X8",
                sparkColor = {1, 1, 1, 1},
            },
            text = {
                showText = true,
                textJustify = "LEFT",
                timeJustify = "RIGHT",
                showTime = true,
                timeFormat = "%.1f",
                textsize = 12,
                timesize = 12,
                textColor = {1, 1, 1, 1},
                timeColor = {1, 1, 1, 1},
            }, 
            position = {
                anchorParent = "MilaUI_Player",
                anchorTo = "BOTTOM",
                anchorFrom = "TOP", 
                xOffset = 0,
                yOffset = -20
            }
        },
        Buffs = {
            Enabled             = false,
            Size                = 32,
            Spacing             = 1,
            Num                 = 7,
            AnchorFrom          = "TOPLEFT",
            AnchorTo            = "BOTTOMLEFT",
            AnchorFrame         = "PowerBar",
            XOffset             = 0,
            YOffset             = 0,
            GrowthX             = "RIGHT",
            GrowthY             = "DOWN",
            Count               = {
                FontSize        = 12,
                Font            = "Friz Quadrata TT",
                FontFlags       = "OUTLINE",
                XOffset         = 0,
                YOffset         = 3,
                AnchorFrom     = "BOTTOMRIGHT",
                AnchorTo       = "BOTTOMRIGHT",
                Colour        = {1, 1, 1, 1},
            },
            OnlyShowPlayer     = false,
            ShowStealableBuffs = true,
            OnlyShowBoss     = true,
            Blacklist = false,
            appliedBlacklist = {},
            Whitelist = false,
            appliedWhitelist = {},
        },
        Debuffs = {
            Enabled             = false,
            Size                = 32,
            Spacing             = 1,
            Num                 = 7,
            AnchorFrom          = "TOPLEFT",
            AnchorTo            = "BOTTOMLEFT",
            AnchorFrame         = "Buffs",
            SmartAnchoring      = true,
            XOffset             = 0,
            YOffset             = 0,
            GrowthX             = "RIGHT",
            GrowthY             = "DOWN",
            Count               = {
                FontSize        = 12,
                Font            = "Friz Quadrata TT",
                FontFlags       = "OUTLINE",
                XOffset         = 0,
                YOffset         = 3,
                AnchorFrom      = "BOTTOMRIGHT",
                AnchorTo        = "BOTTOMRIGHT",
                Colour        = {1, 1, 1, 1},
            },
            OnlyShowPlayer     = false,
            OnlyShowBoss     = true,
            Blacklist = false,
            appliedBlacklist = {},
            Whitelist = false,
            appliedWhitelist = {},
        },
        TargetMarker = {
            Enabled             = true,
            Size                = 24,
            XOffset             = 0,
            YOffset             = 0,
            AnchorFrom          = "CENTER",
            AnchorTo            = "TOP",
        },
        CombatIndicator = {
            Enabled             = true,
            Size                = 24,
            XOffset             = -30,
            YOffset             = 0,
            AnchorFrom          = "CENTER",
            AnchorTo            = "RIGHT",
        },
        LeaderIndicator = {
            Enabled             = true,
            Size                = 16,
            XOffset             = 7,
            YOffset             = 0,
            AnchorFrom          = "LEFT",
            AnchorTo            = "TOPLEFT",
        },
        Texts = {
            First = {
                AnchorTo        = "TOPLEFT",
                AnchorFrom      = "LEFT",
                Colour         = {1, 1, 1, 1},
                FontSize        = 16,
                XOffset         = 23,
                YOffset         = 0,
                Tag             = "[name]",
            },
            Second = {
                AnchorTo        = "CENTER",
                AnchorFrom      = "CENTER",
                Colour         = {1, 1, 1, 1},
                FontSize        = 14,
                XOffset         = 0,
                YOffset         = 0,
                Tag             = "[Health:CurHPwithPerHP]",
            },
            Third = {
                AnchorTo        = "CENTER",
                AnchorFrom      = "CENTER",
                Colour         = {1, 1, 1, 1},
                FontSize        = 12,
                XOffset         = 0,
                YOffset         = -28,
                Tag             = "[Power:PerPP]",
            },
        },
    },
    Target = {
        Frame = {
            Enabled             = true,
            CustomScale         = false,
            Scale               = 1,
            Width               = 230,
            Height              = 38,
            XPosition           = 300,
            YPosition           = -150,
            AnchorFrom          = "CENTER",
            AnchorTo            = "CENTER",
            AnchorParent        = "UIParent",
        },
        Portrait = {
            Enabled         = false,
            Size            = 42,
            XOffset         = -1,
            YOffset         = 0,
            AnchorFrom      = "LEFT",
            AnchorTo        = "RIGHT",
        },
        Health = {
            Width               = 230,
            Height              = 38,
            Direction           = "LR",
            Texture             = "Smooth",
            BackgroundTexture   = "Smooth",
            Colors = {
                ColorByStaticColor                = false,
                StaticColor                       = {1, 1, 1},
                ColourByClass                     = true,
                ColourByReaction                  = true,
                ColourIfDisconnected              = true,
                ColourIfTapped                    = true,
                ColorBackgroundByStaticColor      = false,
                BackgroundStaticColor             = {1, 1, 1},
                ColourBackgroundByForeground      = false,
                ColourBackgroundByClass           = false,
                ColourBackgroundIfDead            = false,
                BackgroundMultiplier              = 0.25,
                Status = {
                    [1] = {255/255, 64/255, 64/255},           -- Dead
                    [2] = {153/255, 153/255, 153/255}, -- Tapped 
                    [3] = {0.6, 0.6, 0.6}, -- Disconnected
                }
                
            },
            CustomMask = {
                Enabled = true,
                MaskTexture = "Interface\\Addons\\Mila_UI\\Media\\Statusbars\\Masks\\parallelogram_style2_mirrored.tga",
            },
            CustomBorder = {
                Enabled = true,
                BorderTexture = "Interface\\Addons\\Mila_UI\\Media\\Borders\\Custom\\border_style2_mirrored.tga",
            },
            HealthPrediction = {
                Enabled = true,
                IncomingHeals = {},
                HealAbsorbs = {
                    Enabled = true,
                    Colour = {128/255, 64/255, 255/255, 1},
                },
                Absorbs = {
                    Enabled         = true,
                    Colour          = {255/255, 205/255, 0/255, 1},
                    ColourByType    = true,
                }
            }
        },
        PowerBar = {
            Width                   = 219,
            Height                  = 19,
            Direction               = "LR",
            Texture                 = "Smooth",
            BackgroundTexture       = "Smooth",
            XPosition               = 0,
            YPosition               = 0,
            AnchorFrom              = "TOPLEFT",
            AnchorTo                = "BOTTOMLEFT",
            AnchorParent            = "MilaUI_Target",
            CustomMask = {
                Enabled         = true,
                MaskTexture     = "Interface\\Addons\\Mila_UI\\Media\\Statusbars\\Masks\\parallelogram_power_style2_mirrored.tga",
            },
            CustomBorder = {
                Enabled         = true,
                BorderTexture   = "Interface\\Addons\\Mila_UI\\Media\\Borders\\Custom\\power_border_style2_mirrored.tga",
            },
            Enabled                 = true,
            ColourByType            = true,
            ColourBackgroundByType  = true,
            BackgroundMultiplier    = 0.25,
            Colour                  = {0/255, 0/255, 1/255, 1},
            BackgroundColour        = {26 / 255, 26 / 255, 26 / 255, 1},
            Smooth = false,
        },
        Castbar = {
            enabled = true,
            CustomScale = false,
            Scale = 1,
            border = false,
            CustomMask = {
                Enabled         = true,
                MaskTexture     = "Interface\\Addons\\Mila_UI\\Media\\Statusbars\\Masks\\parallelogram_power_style2_mirrored.tga",
            },
            CustomBorder = {
                Enabled         = true,
                BorderTexture   = "Interface\\Addons\\Mila_UI\\Media\\Borders\\Custom\\power_border_style2_mirrored.tga",
            },
            width = 200,
            height = 20,
            texture = "Smooth",
            backgroundColor = {0.1, 0.1, 0.1, 0.8},
            borderColor = {0, 0, 0, 1},
            borderSize = 1,
            showShield = true,
            timeToHold = 0.5,
            textures = {
                channel = "Smooth",
                cast = "Smooth",
                uninterruptible = "Smooth",
                castcolor = {1, 0.7, 0, 1},
                channelcolor = {0, 0.7, 1, 1},
                uninterruptiblecolor = {0.7, 0, 0, 1},
                failedcolor = {1, 0.3, 0.3, 1},
            },    
            Icon = {
                showIcon = true,
                iconSize = 24,
                iconPosition = "LEFT",    
            },
            Spark = {
                showSpark = true,
                sparkWidth = 10,
                sparkHeight = 30,
                sparkTexture = "Interface\\Buttons\\WHITE8X8",
                sparkColor = {1, 1, 1, 1},
            },
            text = {
                showText = true,
                textJustify = "LEFT",
                timeJustify = "RIGHT",
                showTime = true,
                timeFormat = "%.1f",
                textsize = 12,
                timesize = 12,
                textColor = {1, 1, 1, 1},
                timeColor = {1, 1, 1, 1},
            }, 
            position = {
                anchorTo = "BOTTOM",
                anchorFrom = "TOP", 
                anchorParent = "MilaUI_Target",
                xOffset = 0,
                yOffset = -20
            }
        },
        Buffs = {
            Enabled             = true,
            Size                = 32,
            Spacing             = 1,
            Num                 = 7,
            AnchorFrom          = "TOPLEFT",
            AnchorTo            = "BOTTOMLEFT",
            AnchorFrame         = "PowerBar",
            XOffset             = 10,
            YOffset             = 0,
            GrowthX             = "RIGHT",
            GrowthY             = "DOWN",
            Count               = {
                FontSize        = 12,
                Font            = "Friz Quadrata TT",
                FontFlags       = "OUTLINE",
                XOffset         = 0,
                YOffset         = 3,
                AnchorFrom     = "BOTTOMRIGHT",
                AnchorTo       = "BOTTOMRIGHT",
                Colour        = {1, 1, 1, 1},
            },
            OnlyShowPlayer     = false,
            ShowStealableBuffs = true,
            OnlyShowBoss     = true,
            Blacklist = false,
            appliedBlacklist = {},
            Whitelist = false,
            appliedWhitelist = {},
        },
        Debuffs = {
            Enabled             = false,
            Size                = 32,
            Spacing             = 1,
            Num                 = 3,
            AnchorFrom          = "TOPLEFT",
            AnchorTo            = "BOTTOMLEFT",
            AnchorFrame         = "Buffs",
            SmartAnchoring      = true,
            XOffset             = 0,
            YOffset             = 0,
            GrowthX             = "LEFT",
            GrowthY             = "UP",
            Count               = {
                FontSize        = 12,
                Font            = "Friz Quadrata TT",
                FontFlags       = "OUTLINE",
                XOffset         = 0,
                YOffset         = 3,
                AnchorFrom     = "BOTTOMRIGHT",
                AnchorTo       = "BOTTOMRIGHT",
                Colour        = {1, 1, 1, 1},
            },
            OnlyShowPlayer     = true,
            OnlyShowBoss     = true,
            Blacklist = false,
            appliedBlacklist = {},
            Whitelist = false,
            appliedWhitelist = {},
        },
        TargetMarker = {
            Enabled             = true,
            Size                = 24,
            XOffset             = -3,
            YOffset             = 0,
            AnchorFrom          = "RIGHT",
            AnchorTo            = "TOPRIGHT",
        },
        CombatIndicator = {
            Enabled             = true,
            Size                = 24,
            XOffset             = -30,
            YOffset             = 0,
            AnchorFrom          = "CENTER",
            AnchorTo            = "RIGHT",
        },
        LeaderIndicator = {
            Enabled             = true,
            Size                = 16,
            XOffset             = 7,
            YOffset             = 0,
            AnchorFrom          = "LEFT",
            AnchorTo            = "TOPLEFT",
        },
        Texts = {
            First = {
                AnchorTo        = "TOPRIGHT",
                AnchorFrom      = "RIGHT",
                Colour         = {1, 1, 1, 1},
                FontSize        = 16,
                XOffset         = -15,
                YOffset         = 0,
                Tag             = "[Name:NamewithTargetTarget:LastNameOnly]",
            },
            Second = {
                AnchorTo        = "CENTER",
                AnchorFrom      = "CENTER",
                Colour         = {1, 1, 1, 1},
                FontSize        = 14,
                XOffset         = 0,
                YOffset         = 0,
                Tag             = "[Health:CurHPwithPerHP]",
            },
            Third = {
                AnchorTo        = "CENTER",
                AnchorFrom      = "CENTER",
                Colour         = {1, 1, 1, 1},
                FontSize        = 12,
                XOffset         = 0,
                YOffset         = -28,
                Tag             = "[Power:PerPP]",
            },
        },
    },
    TargetTarget = {
        Frame = {
            Enabled             = false,
            CustomScale         = true,
            Scale               = 0.4,
            Width               = 230,
            Height              = 38,
            XPosition           = 1.1,
            YPosition           = 0,
            AnchorFrom          = "TOPRIGHT",
            AnchorTo            = "BOTTOMRIGHT",
            AnchorParent        = "MilaUI_Target",
        },
        Portrait = {
            Enabled         = false,
            Size            = 42,
            XOffset         = 1,
            YOffset         = 0,
            AnchorFrom      = "LEFT",
            AnchorTo        = "RIGHT",
        },
        Health = {
            Width               = 230,
            Height              = 38,
            Direction           = "LR",
            Texture             = "Smooth",
            BackgroundTexture   = "Smooth",
            Colors = {
                ColorByStaticColor                = false,
                StaticColor                       = {1, 1, 1},
                ColourByClass                     = true,
                ColourByReaction                  = true,
                ColourIfDisconnected              = true,
                ColourIfTapped                    = true,
                ColorBackgroundByStaticColor      = false,
                BackgroundStaticColor             = {1, 1, 1},
                ColourBackgroundByForeground      = false,
                ColourBackgroundByClass           = false,
                ColourBackgroundIfDead            = false,
                BackgroundMultiplier              = 0.25,
                Status = {
                    [1] = {255/255, 64/255, 64/255},           -- Dead
                    [2] = {153/255, 153/255, 153/255}, -- Tapped 
                    [3] = {0.6, 0.6, 0.6}, -- Disconnected
                }
                
            },
            CustomMask = {
                Enabled         = true,
                MaskTexture     = "Interface\\Addons\\Mila_UI\\Media\\Statusbars\\Masks\\parallelogram_style2_mirrored.tga",
            },
            CustomBorder = {
                Enabled         = true,
                BorderTexture   = "Interface\\Addons\\Mila_UI\\Media\\Borders\\Custom\\border_style2_mirrored.tga",
            },
            HealthPrediction = {
                Enabled = false,
                IncomingHeals = {},
                HealAbsorbs = {
                    Enabled = false,
                    Colour = {128/255, 64/255, 255/255, 1},
                },
                Absorbs = {
                    Enabled         = false,
                    Colour          = {255/255, 205/255, 0/255, 1},
                    ColourByType    = true,
                }
            }
        },
        PowerBar = {
            Width                  = 230,
            Height                 = 38,
            XPosition              = 0,
            YPosition              = 0,
            AnchorFrom             = "RIGHT",
            AnchorTo               = "BOTTOMRIGHT",
            AnchorParent           = "UIParent",
            Direction              = "LR",
            Texture                = "Smooth",
            BackgroundTexture      = "Smooth",
            CustomMask = {
                Enabled = true,
                MaskTexture = "Interface\\Addons\\Mila_UI\\Media\\Statusbars\\Masks\\parallelogram_power_style2_mirrored.tga",
            },
            CustomBorder = {
                Enabled = true,
                BorderTexture = "Interface\\Addons\\Mila_UI\\Media\\Borders\\Custom\\power_border_style2_mirrored.tga",
            },
            Enabled                 = false,
            ColourByType            = true,
            ColourBackgroundByType  = true,
            BackgroundMultiplier    = 0.25,
            Colour                  = {0/255, 0/255, 1/255, 1},
            BackgroundColour        = {26 / 255, 26 / 255, 26 / 255, 1},
            Smooth = false,
        },
        Buffs = {
            Enabled             = false,
            Size                = 42,
            Spacing             = 1,
            Num                 = 1,
            AnchorFrom          = "LEFT",
            AnchorTo            = "RIGHT",
            AnchorFrame         = "MilaUI_TargetTarget",
            XOffset             = 1,
            YOffset             = 0,
            GrowthX             = "RIGHT",
            GrowthY             = "UP",
            Count               = {
                FontSize        = 12,
                Font            = "Friz Quadrata TT",
                FontFlags       = "OUTLINE",
                XOffset         = 0,
                YOffset         = 3,
                AnchorFrom     = "BOTTOMRIGHT",
                AnchorTo       = "BOTTOMRIGHT",
                Colour        = {1, 1, 1, 1},
            },
            OnlyShowPlayer     = false,
            ShowStealableBuffs = false,
            OnlyShowBoss     = true,
            Blacklist = false,
            appliedBlacklist = {},
            Whitelist = false,
            appliedWhitelist = {},
        },
        Debuffs = {
            Enabled             = false,
            Size                = 38,
            Spacing             = 1,
            Num                 = 1,
            AnchorFrom          = "LEFT",
            AnchorTo            = "RIGHT",
            AnchorFrame         = "MilaUI_TargetTarget",
            SmartAnchoring      = false,
            XOffset             = 0,
            YOffset             = 0,
            GrowthX             = "RIGHT",
            GrowthY             = "UP",
            Count               = {
                FontSize        = 12,
                Font            = "Friz Quadrata TT",
                FontFlags       = "OUTLINE",
                XOffset         = 0,
                YOffset         = 3,
                AnchorFrom     = "BOTTOMRIGHT",
                AnchorTo       = "BOTTOMRIGHT",
                Colour        = {1, 1, 1, 1},
            },
            OnlyShowPlayer     = false,
            OnlyShowBoss     = true,
            Blacklist = false,
            appliedBlacklist = {},
            Whitelist = false,
            appliedWhitelist = {},
        },
        TargetMarker = {
            Enabled             = true,
            Size                = 24,
            XOffset             = -3,
            YOffset             = 0,
            AnchorFrom          = "RIGHT",
            AnchorTo            = "TOPRIGHT",
        },
        Texts = {
            First = {
                AnchorTo        = "LEFT",
                AnchorFrom      = "LEFT",
                Colour         = {1, 1, 1, 1},
                FontSize        = 12,
                XOffset         = 3,
                YOffset         = 0,
                Tag             = "",
            },
            Second = {
                AnchorTo        = "RIGHT",
                AnchorFrom      = "RIGHT",
                Colour         = {1, 1, 1, 1},
                FontSize        = 12,
                XOffset         = -3,
                YOffset         = 0,
                Tag             = "",
            },
            Third = {
                AnchorTo        = "CENTER",
                AnchorFrom      = "CENTER",
                Colour         = {1, 1, 1, 1},
                FontSize        = 12,
                XOffset         = 0,
                YOffset         = 0,
                Tag             = "[Name:LastNameOnly]",
            },
        }
    },
    Focus = {
        Frame = {
            Enabled             = true,
            CustomScale         = true,
            Scale               = 0.6,
            Width               = 230,
            Height              = 38,
            XPosition           = 0,
            YPosition           = 40.1,
            AnchorFrom          = "BOTTOMLEFT",
            AnchorTo            = "TOPLEFT",
            AnchorParent        = "MilaUI_Target",
        },
        Portrait = {
            Enabled         = false,
            Size            = 42,
            XOffset         = 1,
            YOffset         = 0,
            AnchorFrom      = "LEFT",
            AnchorTo        = "RIGHT",
        },
        Health = {
            Width               = 230,
            Height              = 38,
            Direction           = "LR",
            Texture             = "Smooth",
            BackgroundTexture   = "Smooth",
            Colors = {
                ColourByClass                     = true,
                ColourByReaction                  = true,
                ColourIfDisconnected              = true,
                ColourIfTapped                    = true,
                ColorBackgroundByStaticColor      = false,
                BackgroundStaticColor             = {1, 1, 1},
                ColourBackgroundByForeground      = false,
                ColourBackgroundByClass           = false,
                ColourBackgroundIfDead            = false,
                BackgroundMultiplier              = 0.25,
                Status = {
                    [1] = {255/255, 64/255, 64/255},           -- Dead
                    [2] = {153/255, 153/255, 153/255}, -- Tapped 
                    [3] = {0.6, 0.6, 0.6}, -- Disconnected
                }
                
            },
            CustomMask = {
                Enabled         = true,
                MaskTexture     = "Interface\\Addons\\Mila_UI\\Media\\Statusbars\\Masks\\parallelogram_style2_mirrored.tga",
            },
            CustomBorder = {
                Enabled         = true,
                BorderTexture   = "Interface\\Addons\\Mila_UI\\Media\\Borders\\Custom\\border_style2_mirrored.tga",
            },
            HealthPrediction = {
                Enabled = false,
                IncomingHeals = {},
                HealAbsorbs = {
                    Enabled = false,
                    Colour = {128/255, 64/255, 255/255, 1},
                },
                Absorbs = {
                    Enabled         = true,
                    Colour          = {255/255, 205/255, 0/255, 1},
                    ColourByType    = true,
                }
            }
        },
        PowerBar = {
            Width                  = 219,
            Height                 = 19,
            Direction              = "LR",
            Texture                = "Smooth",
            BackgroundTexture      = "Smooth",
            XPosition              = 0,
            YPosition              = 0,
            AnchorFrom             = "TOPLEFT",
            AnchorTo               = "BOTTOMLEFT",
            AnchorParent           = "MilaUI_Focus",
            CustomMask = {
                Enabled         = true,
                MaskTexture     = "Interface\\Addons\\Mila_UI\\Media\\Statusbars\\Masks\\parallelogram_power_style2_mirrored.tga",
            },
            CustomBorder = {
                Enabled         = true,
                BorderTexture   = "Interface\\Addons\\Mila_UI\\Media\\Borders\\Custom\\power_border_style2_mirrored.tga",
            },
            Enabled                 = true,
            ColourByType            = true,
            ColourBackgroundByType  = true,
            BackgroundMultiplier    = 0.25,
            Colour                  = {0/255, 0/255, 1/255, 1},
            BackgroundColour        = {26 / 255, 26 / 26 / 255, 26 / 255, 1},
            Smooth = false,
        },
        Castbar = {
            enabled = true,
            CustomScale = false,
            Scale = 1,
            border = false,
            CustomMask = {
                Enabled         = true,
                MaskTexture     = "Interface\\Addons\\Mila_UI\\Media\\Statusbars\\Masks\\parallelogram_power_style2_mirrored.tga",
            },
            CustomBorder = {
                Enabled         = true,
                BorderTexture   = "Interface\\Addons\\Mila_UI\\Media\\Borders\\Custom\\power_border_style2_mirrored.tga",
            },
            width = 200,
            height = 20,
            texture = "Smooth",
            backgroundColor = {0.1, 0.1, 0.1, 0.8},
            borderColor = {0, 0, 0, 1},
            borderSize = 1,
            showShield = true,
            timeToHold = 0.5,    
            textures = {
                channel = "Smooth",
                cast = "Smooth",
                uninterruptible = "Smooth",
                castcolor = {1, 0.7, 0, 1},
                channelcolor = {0, 0.7, 1, 1},
                uninterruptiblecolor = {0.7, 0, 0, 1},
                failedcolor = {1, 0.3, 0.3, 1},
            },    
            Icon = {
                showIcon = true,
                iconSize = 24,
                iconPosition = "LEFT",    
            },
            Spark = {
                showSpark = true,
                sparkWidth = 10,
                sparkHeight = 30,
                sparkTexture = "Interface\\Buttons\\WHITE8X8",
                sparkColor = {1, 1, 1, 1},
            },
            text = {
                showText = true,
                textJustify = "LEFT",
                timeJustify = "RIGHT",
                showTime = true,
                timeFormat = "%.1f",
                textsize = 12,
                timesize = 12,
                textColor = {1, 1, 1, 1},
                timeColor = {1, 1, 1, 1},
            }, 
            position = {
                anchorParent = "MilaUI_Focus",
                anchorTo = "BOTTOM",
                anchorFrom = "TOP", 
                xOffset = 0,
                yOffset = -20
            }
        },
        Buffs = {
            Enabled             = false,
            Size                = 42,
            Spacing             = 1,
            Num                 = 1,
            AnchorFrom          = "LEFT",
            AnchorTo            = "RIGHT",
            AnchorFrame         = "MilaUI_Focus",
            XOffset             = 1,
            YOffset             = 0,
            GrowthX             = "RIGHT",
            GrowthY             = "UP",
            Count               = {
                FontSize        = 12,
                Font            = "Friz Quadrata TT",
                FontFlags       = "OUTLINE",
                XOffset         = 0,
                YOffset         = 3,
                AnchorFrom     = "BOTTOMRIGHT",
                AnchorTo       = "BOTTOMRIGHT",
                Colour        = {1, 1, 1, 1},
            },
            OnlyShowPlayer     = false,
            ShowStealableBuffs = true,
            OnlyShowBoss     = true,
            Blacklist = false,
            appliedBlacklist = {},
            Whitelist = false,
            appliedWhitelist = {},
        },
        Debuffs = {
            Enabled             = false,
            Size                = 38,
            Spacing             = 1,
            Num                 = 1,
            AnchorFrom          = "LEFT",
            AnchorTo            = "RIGHT",
            AnchorFrame         = "MilaUI_Focus",
            SmartAnchoring      = false,
            XOffset             = 0,
            YOffset             = 0,
            GrowthX             = "RIGHT",
            GrowthY             = "UP",
            Count               = {
                FontSize        = 12,
                Font            = "Friz Quadrata TT",
                FontFlags       = "OUTLINE",
                XOffset         = 0,
                YOffset         = 3,
                AnchorFrom     = "BOTTOMRIGHT",
                AnchorTo       = "BOTTOMRIGHT",
                Colour        = {1, 1, 1, 1},
            },
            OnlyShowPlayer     = true,
            OnlyShowBoss     = true,
            Blacklist = false,
            appliedBlacklist = {},
            Whitelist = false,
            appliedWhitelist = {},
        },
        TargetMarker = {
            Enabled             = true,
            Size                = 24,
            XOffset             = -3,
            YOffset             = 0,
            AnchorFrom          = "RIGHT",
            AnchorTo            = "TOPRIGHT",
        },
        CombatIndicator = {
            Enabled             = true,
            Size                = 24,
            XOffset             = -30,
            YOffset             = 0,
            AnchorFrom          = "CENTER",
            AnchorTo            = "RIGHT",
        },
        Texts = {
            First = {
                AnchorTo        = "TOPRIGHT",
                AnchorFrom      = "RIGHT",
                Colour         = {1, 1, 1, 1},
                FontSize        = 16,
                XOffset         = -22,
                YOffset         = 0,
                Tag             = "[Name:LastNameOnly]",
            },
            Second = {
                AnchorTo        = "CENTER",
                AnchorFrom      = "CENTER",
                Colour         = {1, 1, 1, 1},
                FontSize        = 14,
                XOffset         = 0,
                YOffset         = 0,
                Tag             = "[Health:CurHPwithPerHP]",
            },
            Third = {
                AnchorTo        = "CENTER",
                AnchorFrom      = "CENTER",
                Colour         = {1, 1, 1, 1},
                FontSize        = 12,
                XOffset         = 0,
                YOffset         = -28,
                Tag             = "[Power:PerPP]",
            },
        }
    },
    FocusTarget = {
        Frame = {
            Enabled             = false,
            CustomScale         = true,
            Scale               = 0.4,
            Width               = 120,
            Height              = 28,
            XPosition           = 0,
            YPosition           = 1.1,
            AnchorFrom          = "BOTTOMLEFT",
            AnchorTo            = "TOPLEFT",
            AnchorParent        = "MilaUI_Focus",
        },
        Portrait = {
            Enabled         = false,
            Size            = 28,
            XOffset         = 1,
            YOffset         = 0,
            AnchorFrom      = "LEFT",
            AnchorTo        = "RIGHT",
        },
        Health = {
            Width               = 120,
            Height              = 28,
            Direction           = "LR",
            Texture             = "Smooth",
            BackgroundTexture   = "Smooth",
            Colors = {
                ColorByStaticColor                = false,
                StaticColor                       = {1, 1, 1},
                ColourByClass                     = true,
                ColourByReaction                  = true,
                ColourIfDisconnected              = true,
                ColourIfTapped                    = true,
                ColorBackgroundByStaticColor      = false,
                BackgroundStaticColor             = {0.17, 0.09, 0.09},
                ColourBackgroundByForeground      = false,
                ColourBackgroundByClass           = false,
                ColourBackgroundIfDead            = false,
                BackgroundMultiplier              = 0.25,
                Status = {
                    [1] = {255/255, 64/255, 64/255},           -- Dead
                    [2] = {153/255, 153/255, 153/255}, -- Tapped 
                    [3] = {0.6, 0.6, 0.6}, -- Disconnected
                }
                
            },
            CustomMask = {
                Enabled         = true,
                MaskTexture     = "Interface\\Addons\\Mila_UI\\Media\\Statusbars\\Masks\\parallelogram_style2_mirrored.tga",
            },
            CustomBorder = {
                Enabled         = true,
                BorderTexture   = "Interface\\Addons\\Mila_UI\\Media\\Borders\\Custom\\border_style2_mirrored.tga",
            },
            HealthPrediction = {
                Enabled = false,
                IncomingHeals = {},
                HealAbsorbs = {
                    Enabled = false,
                    Colour = {128/255, 64/255, 255/255, 1},
                },
                Absorbs = {
                    Enabled         = false,
                    Colour          = {255/255, 205/255, 0/255, 1},
                    ColourByType    = true,
                }
            }
        },
        PowerBar = {
            Width               = 120,
            Height              = 28,
            Direction           = "LR",
            Texture             = "Smooth",
            BackgroundTexture   = "Smooth",
            XPosition           = 0,
            YPosition           = 0,
            AnchorFrom          = "TOPRIGHT",
            AnchorTo            = "BOTTOMRIGHT",
            AnchorParent        = "MilaUI_FocusTarget",
            CustomMask = {
                Enabled         = true,
                MaskTexture     = "Interface\\Addons\\Mila_UI\\Media\\Statusbars\\Masks\\parallelogram_power_style2_mirrored.tga",
            },
            CustomBorder = {
                Enabled         = true,
                BorderTexture   = "Interface\\Addons\\Mila_UI\\Media\\Borders\\Custom\\power_border_style2_mirrored.tga",
            },
            Enabled                 = false,
            ColourByType            = true,
            ColourBackgroundByType  = true,
            BackgroundMultiplier    = 0.25,
            Colour                  = {0/255, 0/255, 1/255, 1},
            BackgroundColour        = {26 / 255, 26 / 255, 26 / 255, 1},
            Smooth = false,
        },
        Buffs = {
            Enabled             = false,
            Size                = 42,
            Spacing             = 1,
            Num                 = 1,
            AnchorFrom          = "LEFT",
            AnchorTo            = "RIGHT",
            AnchorFrame         = "MilaUI_FocusTarget",
            XOffset             = 1,
            YOffset             = 0,
            GrowthX             = "RIGHT",
            GrowthY             = "UP",
            Count               = {
                FontSize        = 12,
                Font            = "Friz Quadrata TT",
                FontFlags       = "OUTLINE",
                XOffset         = 0,
                YOffset         = 3,
                AnchorFrom     = "BOTTOMRIGHT",
                AnchorTo       = "BOTTOMRIGHT",
                Colour        = {1, 1, 1, 1},
            },
            OnlyShowPlayer     = false,
            ShowStealableBuffs = false,
            OnlyShowBoss     = true,
            Blacklist = false,
            appliedBlacklist = {},
            Whitelist = false,
            appliedWhitelist = {},
        },
        Debuffs = {
            Enabled             = false,
            Size                = 38,
            Spacing             = 1,
            Num                 = 1,
            AnchorFrom          = "LEFT",
            AnchorTo            = "RIGHT",
            AnchorFrame         = "MilaUI_FocusTarget",
            SmartAnchoring      = false,
            XOffset             = 0,
            YOffset             = 0,
            GrowthX             = "RIGHT",
            GrowthY             = "UP",
            Count               = {
                FontSize        = 12,
                Font            = "Friz Quadrata TT",
                FontFlags       = "OUTLINE",
                XOffset         = 0,
                YOffset         = 3,
                AnchorFrom     = "BOTTOMRIGHT",
                AnchorTo       = "BOTTOMRIGHT",
                Colour        = {1, 1, 1, 1},
            },
            OnlyShowPlayer     = true,
            OnlyShowBoss     = true,
            Blacklist = false,
            appliedBlacklist = {},
            Whitelist = false,
            appliedWhitelist = {},
        },
        TargetMarker = {
            Enabled             = true,
            Size                = 24,
            XOffset             = -3,
            YOffset             = 0,
            AnchorFrom          = "RIGHT",
            AnchorTo            = "TOPRIGHT",
        },
        Texts = {
            First = {
                AnchorTo        = "CENTER",
                AnchorFrom      = "CENTER",
                Colour         = {1, 1, 1, 1},
                FontSize        = 12,
                XOffset         = 0,
                YOffset         = 0,
                Tag             = "[Name:LastNameOnly]",
            },
            Second = {
                AnchorTo        = "RIGHT",
                AnchorFrom      = "RIGHT",
                Colour         = {1, 1, 1, 1},
                FontSize        = 12,
                XOffset         = -3,
                YOffset         = 0,
                Tag             = "",
            },
            Third = {
                AnchorTo        = "CENTER",
                AnchorFrom      = "CENTER",
                Colour         = {1, 1, 1, 1},
                FontSize        = 12,
                XOffset         = 0,
                YOffset         = 0,
                Tag             = "",
            },
        }
    },
    Pet = {
        Frame = {
            Enabled             = true,
            CustomScale         = true,
            Scale               = 0.4,
            Width               = 230,
            Height              = 19,
            XPosition           = 0,
            YPosition           = -1.1,
            AnchorFrom          = "TOPLEFT",
            AnchorTo            = "BOTTOMLEFT",
            AnchorParent        = "MilaUI_Player",
        },
        Portrait = {
            Enabled         = false,
            Size            = 42,
            XOffset         = -1,
            YOffset         = 0,
            AnchorFrom      = "RIGHT",
            AnchorTo        = "LEFT",
        },
        Health = {
            Width               = 230,
            Height              = 19,
            Direction           = "LR",
            Texture             = "Smooth",
            BackgroundTexture   = "Smooth",
            Colors = {
                ColorByStaticColor                = false,
                StaticColor                       = {1, 1, 1},
                ColourByClass                     = true,
                ColourByReaction                  = true,
                ColourIfDisconnected              = true,
                ColourIfTapped                    = true,
                ColorBackgroundByStaticColor      = false,
                BackgroundStaticColor             = {1, 1, 1},
                ColourBackgroundByForeground      = false,
                ColourBackgroundByClass           = false,
                ColourBackgroundIfDead            = false,
                BackgroundMultiplier              = 0.25,
                Status = {
                    [1] = {255/255, 64/255, 64/255},           -- Dead
                    [2] = {153/255, 153/255, 153/255}, -- Tapped 
                    [3] = {0.6, 0.6, 0.6}, -- Disconnected
                }
                
            },
            CustomMask = {
                Enabled         = true,
                MaskTexture     = "Interface\\Addons\\Mila_UI\\Media\\Statusbars\\Masks\\Parallelogram.tga",
            },
            CustomBorder = {
                Enabled         = true,
                BorderTexture   = "Interface\\Addons\\Mila_UI\\Media\\Borders\\Custom\\border_style2.tga",
            },
            ColourByPlayerClass = false,
            HealthPrediction = {
                Enabled = false,
                IncomingHeals = {},
                HealAbsorbs = {
                    Enabled = false,
                    Colour = {128/255, 64/255, 255/255, 1},
                },
                Absorbs = {
                    Enabled         = false,
                    Colour          = {255/255, 205/255, 0/255, 1},
                    ColourByType    = true,
                }
            }
        },
        PowerBar = {
            Width               = 219,
            Height              = 19,
            Direction           = "LR",
            Texture             = "Smooth",
            BackgroundTexture   = "Smooth",
            XPosition           = 0,
            YPosition           = 0,
            AnchorFrom          = "BOTTOMRIGHT",
            AnchorTo            = "TOPRIGHT",
            AnchorParent        = "MilaUI_Pet",
            CustomMask = {
                Enabled         = true,
                MaskTexture     = "Interface\\Addons\\Mila_UI\\Media\\Statusbars\\Masks\\parallelogram_power_style2_mirrored.tga",
            },
            CustomBorder = {
                Enabled         = true,
                BorderTexture   = "Interface\\Addons\\Mila_UI\\Media\\Borders\\Custom\\power_border_style2_mirrored.tga",
            },
            Enabled                 = false,
            Height                  = 5,
            ColourByType            = true,
            ColourBackgroundByType  = true,
            BackgroundMultiplier    = 0.25,
            Colour                  = {0/255, 0/255, 1/255, 1},
            BackgroundColour        = {26 / 255, 26 / 255, 26 / 255, 1},
            Smooth = false,
        },
        Castbar = {
            border = false,
            CustomMask = {
                Enabled = true,
                MaskTexture = "Interface\\Addons\\Mila_UI\\Media\\Statusbars\\Masks\\parallelogram_power_style2.tga",
            },
            CustomBorder = {
                Enabled = true,
                BorderTexture = "Interface\\Addons\\Mila_UI\\Media\\Borders\\Custom\\power_border_style2.tga",
            },
            enabled = true,
            width = 200,
            height = 20,
            texture = "Interface\\RaidFrame\\Raid-Bar-Hp-Fill",
            backgroundColor = {0.1, 0.1, 0.1, 0.8},
            borderColor = {0, 0, 0, 1},
            borderSize = 1,
            showShield = true,
            timeToHold = 0.5,         -- How long to show failed/interrupted casts
            hideTradeSkills = false,  -- Whether to hide profession casts
            textures = {
                channel = "Smooth",
                cast = "Smooth",
                uninterruptible = "Smooth",
                castcolor = {1, 0.7, 0, 1},
                channelcolor = {0, 0.7, 1, 1},
                uninterruptiblecolor = {0.7, 0, 0, 1},
                failedcolor = {1, 0.3, 0.3, 1},
            },
            Icon = {
                showIcon = true,
                iconSize = 24,
                iconPosition = "LEFT",    -- LEFT or RIGHT
            },
            Spark = {
                showSpark = true,
                sparkWidth = 10,
                sparkHeight = 30,
                sparkTexture = "Interface\\Buttons\\WHITE8X8",
                sparkColor = {1, 1, 1, 1},
            },
            text = {
                showText = true,
                textJustify = "LEFT",
                timeJustify = "RIGHT",
                showTime = true,
                timeFormat = "%.1f",
                textsize = 12,
                timesize = 12,
                textColor = {1, 1, 1, 1},
                timeColor = {1, 1, 1, 1},
            }, 
            position = {
                anchorParent = "MilaUI_Pet",
                anchorTo = "BOTTOM",
                anchorFrom = "TOP", 
                xOffset = 0,
                yOffset = -20
            }
        },
        Buffs = {
            Enabled             = false,
            Size                = 38,
            Spacing             = 1,
            Num                 = 7,
            AnchorFrom          = "TOPLEFT",
            AnchorTo            = "BOTTOMLEFT",
            AnchorFrame         = "MilaUI_Pet",
            XOffset             = 0,
            YOffset             = -1,
            GrowthX             = "RIGHT",
            GrowthY             = "DOWN",
            Count               = {
                FontSize        = 12,
                Font            = "Friz Quadrata TT",
                FontFlags       = "OUTLINE",
                XOffset         = 0,
                YOffset         = 3,
                AnchorFrom     = "BOTTOMRIGHT",
                AnchorTo       = "BOTTOMRIGHT",
                Colour        = {1, 1, 1, 1},
            },
            OnlyShowPlayer     = false,
            ShowStealableBuffs = false,
            OnlyShowBoss     = true,
            Blacklist = false,
            appliedBlacklist = {},
            Whitelist = false,
            appliedWhitelist = {},
        },
        Debuffs = {
            Enabled             = false,
            Size                = 38,
            Spacing             = 1,
            Num                 = 7,
            AnchorFrom          = "TOPLEFT",
            AnchorTo            = "BOTTOMLEFT",
            AnchorFrame         = "MilaUI_Pet",
            SmartAnchoring      = false,
            XOffset             = 0,
            YOffset             = -1,
            GrowthX             = "RIGHT",
            GrowthY             = "DOWN",
            Count               = {
                FontSize        = 12,
                Font            = "Friz Quadrata TT",
                FontFlags       = "OUTLINE",
                XOffset         = 0,
                YOffset         = 3,
                AnchorFrom     = "BOTTOMRIGHT",
                AnchorTo       = "BOTTOMRIGHT",
                Colour        = {1, 1, 1, 1},
            },
            OnlyShowPlayer     = false,
            OnlyShowBoss     = true,
            Blacklist = false,
            appliedBlacklist = {},
            Whitelist = false,
            appliedWhitelist = {},
        },
        TargetMarker = {
            Enabled             = false,
            Size                = 24,
            XOffset             = 0,
            YOffset             = 0,
            AnchorFrom          = "CENTER",
            AnchorTo            = "CENTER",
        },
        Texts = {
            First = {
                AnchorTo        = "LEFT",
                AnchorFrom      = "LEFT",
                Colour         = {1, 1, 1, 1},
                FontSize        = 12,
                XOffset         = 3,
                YOffset         = 0,
                Tag             = "",
            },
            Second = {
                AnchorTo        = "RIGHT",
                AnchorFrom      = "RIGHT",
                Colour         = {1, 1, 1, 1},
                FontSize        = 12,
                XOffset         = -3,
                YOffset         = 0,
                Tag             = "",
            },
            Third = {
                AnchorTo        = "CENTER",
                AnchorFrom      = "CENTER",
                Colour         = {1, 1, 1, 1},
                FontSize        = 12,
                XOffset         = 0,
                YOffset         = 0,
                Tag             = "",
            },
        }
    },
    Boss = {
        Frame = {
            Enabled             = true,
            CustomScale         = false,
            Scale               = 1,
            Width               = 230,
            Height              = 38,
            XPosition           = 750.1,
            YPosition           = 0.1,
            Spacing             = 26.1,
            AnchorFrom          = "CENTER",
            AnchorTo            = "CENTER",
            AnchorParent        = "UIParent",
            GrowthY             = "DOWN",
        },
        Portrait = {
            Enabled         = false,
            Size            = 42,
            XOffset         = -1,
            YOffset         = 0,
            AnchorFrom      = "RIGHT",
            AnchorTo        = "LEFT",
        },
        Health = {
            Width               = 230,
            Height              = 38,
            Direction           = "LR",
            Texture             = "Smooth",
            BackgroundTexture   = "Smooth",
            Colors = {
                ColorByStaticColor                = false,
                StaticColor                       = {1, 1, 1},
                ColourByClass                     = true,
                ColourByReaction                  = true,
                ColourIfDisconnected              = true,
                ColourIfTapped                    = true,
                ColorBackgroundByStaticColor      = false,
                BackgroundStaticColor             = {1, 1, 1},
                ColourBackgroundByForeground      = false,
                ColourBackgroundByClass           = false,
                ColourBackgroundIfDead            = false,
                BackgroundMultiplier              = 0.25,
                Status = {
                    [1] = {255/255, 64/255, 64/255},           -- Dead
                    [2] = {153/255, 153/255, 153/255}, -- Tapped 
                    [3] = {0.6, 0.6, 0.6}, -- Disconnected
                }
                
            },
            CustomMask = {
                Enabled         = true,
                MaskTexture     = "Interface\\Addons\\Mila_UI\\Media\\Statusbars\\Masks\\parallelogram_style2_mirrored.tga",
            },
            CustomBorder = {
                Enabled         = true,
                BorderTexture   = "Interface\\Addons\\Mila_UI\\Media\\Borders\\Custom\\border_style2_mirrored.tga",
            },
            HealthPrediction = {
                Enabled = true,
                IncomingHeals = {},
                HealAbsorbs = {
                    Enabled = true,
                    Colour = {128/255, 64/255, 255/255, 1},
                },
                Absorbs = {
                    Enabled         = true,
                    Colour          = {255/255, 205/255, 0/255, 1},
                    ColourByType    = true,
                }
            }
        },
        PowerBar = {
            Width               = 219,
            Height              = 19,
            Direction           = "LR",
            Texture             = "Smooth",
            BackgroundTexture   = "Smooth",
            XPosition           = 0,
            YPosition           = 0,
            AnchorFrom          = "BOTTOMRIGHT",
            AnchorTo            = "TOPRIGHT",
            AnchorParent        = "MilaUI_Boss",
            CustomMask = {
                Enabled         = true,
                MaskTexture     = "Interface\\Addons\\Mila_UI\\Media\\Statusbars\\Masks\\parallelogram_power_style2_mirrored.tga",
            },
            CustomBorder = {
                Enabled         = true,
                BorderTexture   = "Interface\\Addons\\Mila_UI\\Media\\Borders\\Custom\\power_border_style2_mirrored.tga",
            },
            Enabled                 = true,
            ColourByType            = true,
            ColourBackgroundByType  = true,
            BackgroundMultiplier    = 0.25,
            Colour                  = {0/255, 0/255, 1/255, 1},
            BackgroundColour        = {26 / 255, 26 / 26 / 255, 26 / 255, 1},
            Smooth = false,
        },
        Castbar = {
            enabled = true,
            border = false,
            CustomScale = false,
            Scale = 1,
            CustomMask = {
                Enabled         = true,
                MaskTexture     = "Interface\\Addons\\Mila_UI\\Media\\Statusbars\\Masks\\parallelogram_power_style2_mirrored.tga",
            },
            CustomBorder = {
                Enabled         = true,
                BorderTexture   = "Interface\\Addons\\Mila_UI\\Media\\Borders\\Custom\\power_border_style2_mirrored.tga",
            },
            width = 200,
            height = 20,
            texture = "Smooth",
            backgroundColor = {0.1, 0.1, 0.1, 0.8},
            borderColor = {0, 0, 0, 1},
            borderSize = 1,
            showShield = true,
            timeToHold = 0.5,    
            textures = {
                channel = "Smooth",
                cast = "Smooth",
                uninterruptible = "Smooth",
                castcolor = {1, 0.7, 0, 1},
                channelcolor = {0, 0.7, 1, 1},
                uninterruptiblecolor = {0.7, 0, 0, 1},
                failedcolor = {1, 0.3, 0.3, 1},
            },    
            Icon = {
                showIcon = true,
                iconSize = 24,
                iconPosition = "LEFT",    
            },
            Spark = {
                showSpark = true,
                sparkWidth = 10,
                sparkHeight = 30,
                sparkTexture = "Interface\\Buttons\\WHITE8X8",
                sparkColor = {1, 1, 1, 1},
            },
            text = {
                showText = true,
                textJustify = "LEFT",
                timeJustify = "RIGHT",
                showTime = true,
                timeFormat = "%.1f",
                textsize = 12,
                timesize = 12,
                textColor = {1, 1, 1, 1},
                timeColor = {1, 1, 1, 1},
            }, 
            position = {
                anchorParent = "MilaUI_Boss",
                anchorTo = "BOTTOM",
                anchorFrom = "TOP", 
                xOffset = 0,
                yOffset = -20
            }
        },
        Buffs = {
            Enabled             = true,
            Size                = 42,
            Spacing             = 1,
            Num                 = 3,
            AnchorFrom          = "LEFT",
            AnchorTo            = "RIGHT",
            AnchorFrame         = "MilaUI_Boss",
            XOffset             = 1,
            YOffset             = 0,
            GrowthX             = "RIGHT",
            GrowthY             = "UP",
            Count               = {
                FontSize        = 12,
                Font            = "Friz Quadrata TT",
                FontFlags       = "OUTLINE",
                XOffset         = 0,
                YOffset         = 3,
                AnchorFrom     = "BOTTOMRIGHT",
                AnchorTo       = "BOTTOMRIGHT",
                Colour        = {1, 1, 1, 1},
            },
            OnlyShowPlayer     = true,
            ShowStealableBuffs = true,
            OnlyShowBoss     = true,
            Blacklist = false,
            appliedBlacklist = {},
            Whitelist = false,
            appliedWhitelist = {},
        },
        Debuffs = {
            Enabled             = false,
            Size                = 42,
            Spacing             = 1,
            Num                 = 1,
            AnchorFrom          = "RIGHT",
            AnchorTo            = "LEFT",
            AnchorFrame         = "MilaUI_Boss",
            SmartAnchoring      = false,
            XOffset             = -1,
            YOffset             = 0,
            GrowthX             = "LEFT",
            GrowthY             = "UP",
            Count               = {
                FontSize        = 12,
                Font            = "Friz Quadrata TT",
                FontFlags       = "OUTLINE",
                XOffset         = 0,
                YOffset         = 3,
                AnchorFrom     = "BOTTOMRIGHT",
                AnchorTo       = "BOTTOMRIGHT",
                Colour        = {1, 1, 1, 1},
            },
            OnlyShowPlayer     = true,
            OnlyShowBoss     = true,
            Blacklist = false,
            appliedBlacklist = {},
            Whitelist = false,
            appliedWhitelist = {},
        },
        TargetMarker = {
            Enabled             = true,
            Size                = 24,
            XOffset             = -3,
            YOffset             = 0,
            AnchorFrom          = "RIGHT",
            AnchorTo            = "TOPRIGHT",
        },
        TargetIndicator = {
            Enabled            = true,
        },
        Texts = {
            First = {
                AnchorTo        = "LEFT",
                AnchorFrom      = "LEFT",
                Colour         = {1, 1, 1, 1},
                FontSize        = 12,
                XOffset         = 3,
                YOffset         = 0,
                Tag             = "[Name:LastNameOnly]",
            },
            Second = {
                AnchorTo        = "RIGHT",
                AnchorFrom      = "RIGHT",
                Colour         = {1, 1, 1, 1},
                FontSize        = 12,
                XOffset         = -3,
                YOffset         = 0,
                Tag             = "[Health:CurHPwithPerHP]",
            },
            Third = {
                AnchorTo        = "CENTER",
                AnchorFrom      = "CENTER",
                Colour         = {1, 1, 1, 1},
                FontSize        = 12,
                XOffset         = 0,
                YOffset         = 0,
                Tag             = "",
            },
        }
    }
}