local LSM = LibStub("LibSharedMedia-3.0") 
local IsAddOnLoaded = _G.C_AddOns and _G.C_AddOns.IsAddOnLoaded or _G.IsAddOnLoaded

if LSM == nil then return end

-- Register the MilaUI logo
LSM:Register("background", "MilaUI-Logo", [[Interface\Addons\MilaUI\Media\logo.tga]])
LSM:Register("statusbar", "a-Mila Backdrop", [[Interface\Addons\MilaUI\Media\Statusbars\Mila_Backdrop.tga]])
LSM:Register("statusbar", "a-Mila Target Backdrop", [[Interface\Addons\MilaUI\Media\Statusbars\Mila_target_backdrop.tga]])
LSM:Register("statusbar", "a-Mila Target CosmeticBG", [[Interface\Addons\MilaUI\Media\Statusbars\Masks\parallelogram.tga]])
LSM:Register("statusbar", "a-Mila Player CosmeticBG", [[Interface\Addons\MilaUI\Media\Statusbars\Masks\parallelogram2.tga]])
LSM:Register('statusbar', 'a-Mila', [[Interface\Addons\MilaUI\Media\Statusbars\Mila1.tga]])
LSM:Register('statusbar', 'a-Mila1', [[Interface\Addons\MilaUI\Media\Statusbars\Mila2.tga]])
LSM:Register('statusbar', 'a-Mila2', [[Interface\Addons\MilaUI\Media\Statusbars\Mila3.tga]])
LSM:Register('statusbar', 'a-Mila3', [[Interface\Addons\MilaUI\Media\Statusbars\Mila4.tga]])
LSM:Register('statusbar', 'a-Mila4', [[Interface\Addons\MilaUI\Media\Statusbars\Mila5.tga]])
LSM:Register('statusbar', 'a-Mila5', [[Interface\Addons\MilaUI\Media\Statusbars\Mila6.tga]])
LSM:Register('statusbar', 'a-Mila6', [[Interface\Addons\MilaUI\Media\Statusbars\Mila7.tga]])
LSM:Register("font", "Mila UI SC", [[Interface\Addons\MilaUI\Media\Font\Black Desert SC.ttf]]) 
LSM:Register("font", "Mila UI", [[Interface\Addons\MilaUI\Media\Font\Black Desert.ttf]])
LSM:Register("statusbar", "a-Para2", [[Interface\Addons\MilaUI\Media\Statusbars\Masks\paralellogram2.tga]])
LSM:Register("statusbar", "b-Mila Health 01", [[Interface\Addons\MilaUI\Media\Statusbars\Mila_health01.tga]])
LSM:Register("statusbar", "b-Mila Health Target 01", [[Interface\Addons\MilaUI\Media\Statusbars\Mila_health_target01.tga]])
LSM:Register("statusbar", "b-Mila Health 02", [[Interface\Addons\MilaUI\Media\Statusbars\Mila_health02.tga]]) 
LSM:Register("statusbar", "b-Mila Health Target 02", [[Interface\Addons\MilaUI\Media\Statusbars\Mila_health_target02.tga]]) 
LSM:Register("statusbar", "b-Mila Health 03", [[Interface\Addons\MilaUI\Media\Statusbars\Mila_health03.tga]])
LSM:Register("statusbar", "b-Mila Health 03 Target", [[Interface\Addons\MilaUI\Media\Statusbars\Mila_health_target03.tga]])  
LSM:Register("statusbar", "b-Mila Health Color", [[Interface\Addons\MilaUI\Media\Statusbars\Mila_health_color.tga]]) 
LSM:Register("statusbar", "b-Mila Health Glow 01", [[Interface\Addons\MilaUI\Media\Statusbars\Mila_health_glow01.tga]]) 
LSM:Register("statusbar", "b-Mila Health Glow 02", [[Interface\Addons\MilaUI\Media\Statusbars\Mila_health_glow02.tga]]) 
LSM:Register("statusbar", "b-Mila Health Loss 01", [[Interface\Addons\MilaUI\Media\Statusbars\health_bd.tga]])
LSM:Register("statusbar", "b-Mila Power 01", [[Interface\Addons\MilaUI\Media\Statusbars\Mila_power01.tga]]) 
LSM:Register("statusbar", "b-Mila Power Target 01", [[Interface\Addons\MilaUI\Media\Statusbars\Mila_power_target01.tga]])
LSM:Register("statusbar", "b-Mila Power 02", [[Interface\Addons\MilaUI\Media\Statusbars\Mila_power02.tga]]) 
LSM:Register("statusbar", "b-Mila Power Target 02", [[Interface\Addons\MilaUI\Media\Statusbars\Mila_power_target02.tga]])
LSM:Register("statusbar", "b-Mila Power 03", [[Interface\Addons\MilaUI\Media\Statusbars\Mila_power03.tga]]) 
LSM:Register("statusbar", "b-Mila Power Target 03", [[Interface\Addons\MilaUI\Media\Statusbars\Mila_power_target03.tga]])
LSM:Register("statusbar", "b-Mila Power Class", [[Interface\Addons\MilaUI\Media\Statusbars\Mila_power_class.tga]]) 
LSM:Register("statusbar", "b-Mila Power Energy", [[Interface\Addons\MilaUI\Media\Statusbars\Mila_power_energy.tga]])
LSM:Register("statusbar", "b-Mila Power Energy Target", [[Interface\Addons\MilaUI\Media\Statusbars\Mila_power_energy_target.tga]])  
LSM:Register("statusbar", "b-Mila Power Focus", [[Interface\Addons\MilaUI\Media\Statusbars\Mila_power_focus.tga]])
LSM:Register("statusbar", "b-Mila Power Focus Target", [[Interface\Addons\MilaUI\Media\Statusbars\Mila_power_focus_target.tga]]) 
LSM:Register("statusbar", "b-Mila Power Fury", [[Interface\Addons\MilaUI\Media\Statusbars\Mila_power_fury.tga]])
LSM:Register("statusbar", "b-Mila Power Fury Target", [[Interface\Addons\MilaUI\Media\Statusbars\Mila_power_fury_target.tga]])  
LSM:Register("statusbar", "b-Mila Power Rage", [[Interface\Addons\MilaUI\Media\Statusbars\Mila_power_rage.tga]]) 
LSM:Register("statusbar", "b-Mila Power Rage Target", [[Interface\Addons\MilaUI\Media\Statusbars\Mila_power_rage_target.tga]])
LSM:Register("statusbar", "b-Mila Power Runic", [[Interface\Addons\MilaUI\Media\Statusbars\Mila_power_runic.tga]]) 
LSM:Register("statusbar", "b-Mila Player Castbar", [[Interface\Addons\MilaUI\Media\Statusbars\Mila_player_castbar.tga]])
LSM:Register("statusbar", "ElvUI Norm", [[Interface\Addons\MilaUI\Media\Statusbars\NormTex2.tga]])
LSM:Register("statusbar", "ElvUI Norm1", [[Interface\Addons\MilaUI\Media\Statusbars\NormTex3.tga]])
LSM:Register("statusbar", "ElvUI Gloss", [[Interface\Addons\MilaUI\Media\Statusbars\NormTex.tga]])
LSM:Register("statusbar", "ElvUI Blank", [[Interface\Addons\MilaUI\Media\Statusbars\White8x8.tga]])
LSM:Register("statusbuar", "Minimalist", [[Interface\Addons\MilaUI\Media\Statusbars\Minimalist.tga]])
LSM:Register("statusbuar", "Melli", [[Interface\Addons\MilaUI\Media\Statusbars\Melli.tga]])
LSM:Register("background", "ElvUI Blank", [[Interface\Addons\MilaUI\Media\Statusbars\White8x8.tga]])
